# Generated by Django 4.2.7 on 2023-12-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teme_Materii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_tema', models.CharField(max_length=100)),
                ('text_tema', models.CharField(max_length=10000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume_materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etapa1.materie')),
            ],
        ),
    ]
