# Generated by Django 4.2.7 on 2023-12-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('descriere', models.TextField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etapa1.materie')),
            ],
        ),
    ]
